import React from 'react';
import { useForm } from '../../hooks/useForm';
import RadioGroup from '../FormFields/RadioGroup';
import TextAreaField from '../FormFields/TextAreaField';

export default function Tab5IP({ readOnly }) {
  const { formData, updateField } = useForm();
  const onChange = (name, value) => updateField('formData', name, value);

  return (
    <div>
      <div className="panel-header">
        <h2>Section 3 &mdash; Intellectual Property</h2>
        <div className="panel-subtitle">All Submissions</div>
      </div>
      <div className="panel-body">
        <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', marginBottom: 16 }}>
          Answer each question below to the best of your knowledge. Select <strong>"Not known"</strong> if you are unsure.
        </p>

        <RadioGroup label="1. Who will own the outputs generated by this tool?" name="ipOwnership" value={formData.ipOwnership} onChange={onChange} readOnly={readOnly}
          options={[
            { value: 'firm', label: 'Our firm / team retains full ownership' },
            { value: 'vendor', label: 'The vendor retains some or all ownership rights' },
            { value: 'shared', label: 'Shared / joint ownership' },
            { value: 'notKnown', label: 'Not known' },
          ]}
        />
        <RadioGroup label="2. Could the AI-generated output contain content that infringes on third-party IP?" name="ipInfringement" value={formData.ipInfringement} onChange={onChange} readOnly={readOnly}
          options={[
            { value: 'yes', label: 'Yes — there is a possibility' },
            { value: 'no', label: 'No — outputs are unlikely to infringe' },
            { value: 'notKnown', label: 'Not known' },
          ]}
        />
        <RadioGroup label="3. Does the vendor provide indemnification against IP infringement claims?" name="ipIndemnify" value={formData.ipIndemnify} onChange={onChange} readOnly={readOnly}
          options={[
            { value: 'yes', label: 'Yes' },
            { value: 'no', label: 'No' },
            { value: 'na', label: 'Not applicable (in-house built)' },
            { value: 'notKnown', label: 'Not known' },
          ]}
        />
        <RadioGroup label="4. Are there plagiarism or originality checks in place?" name="ipPlagiarism" value={formData.ipPlagiarism} onChange={onChange} readOnly={readOnly}
          options={[
            { value: 'yes', label: 'Yes — automated or manual checks are in place' },
            { value: 'no', label: 'No — no plagiarism controls currently' },
            { value: 'notKnown', label: 'Not known' },
          ]}
        />
        <RadioGroup label="5. Will confidential or proprietary information be entered as prompts or inputs?" name="ipConfidential" value={formData.ipConfidential} onChange={onChange} readOnly={readOnly}
          options={[
            { value: 'yes', label: 'Yes' },
            { value: 'no', label: 'No — only public or non-sensitive data' },
            { value: 'notKnown', label: 'Not known' },
          ]}
        />
        <RadioGroup label="6. Could the tool's outputs be used in client deliverables or external-facing documents?" name="ipExternalUse" value={formData.ipExternalUse} onChange={onChange} readOnly={readOnly}
          options={[
            { value: 'yes', label: 'Yes' },
            { value: 'no', label: 'No — internal use only' },
            { value: 'notKnown', label: 'Not known' },
          ]}
        />
        <RadioGroup label="7. Is the team aware of restrictions on how AI-generated content can be used?" name="ipRestrictions" value={formData.ipRestrictions} onChange={onChange} readOnly={readOnly}
          options={[
            { value: 'yes', label: 'Yes — restrictions are understood' },
            { value: 'no', label: 'No — no restrictions identified' },
            { value: 'notKnown', label: 'Not known' },
          ]}
        />
        <RadioGroup label="8. Has the team received guidance on safe prompt practices to avoid IP leakage?" name="ipTraining" value={formData.ipTraining} onChange={onChange} readOnly={readOnly}
          options={[
            { value: 'yes', label: 'Yes' },
            { value: 'no', label: 'No' },
            { value: 'planned', label: 'Planned but not yet delivered' },
            { value: 'notKnown', label: 'Not known' },
          ]}
        />
        <TextAreaField label="Additional IP comments or concerns (optional)" name="ipComments" value={formData.ipComments} onChange={onChange} readOnly={readOnly} placeholder="Any additional context for the review team..." />
      </div>
    </div>
  );
}
